/**
 * VOICEVOX 音声生成スクリプト
 * script.ts の各セグメントに対してVOICEVOX APIで音声を生成
 */

import fs from "fs";
import path from "path";
import { loadConfig, getCharacterConfig, getVoicevoxEndpoint } from "../src/config.js";
import type { ScriptData, DurationsJson } from "../src/types.js";

const VOICES_DIR = path.resolve(process.cwd(), "public/voices");
const SCRIPT_PATH = path.resolve(process.cwd(), "src/data/script.ts");
const DURATIONS_PATH = path.join(VOICES_DIR, "durations.json");

/**
 * WAVファイルの再生時間を取得（秒）
 */
function getWavDuration(wavPath: string): number {
  const buffer = fs.readFileSync(wavPath);

  // WAVヘッダーからサンプルレートとデータサイズを取得
  // bytes 24-27: sample rate (little endian)
  // bytes 40-43: data chunk size (little endian)
  const sampleRate = buffer.readUInt32LE(24);
  const bitsPerSample = buffer.readUInt16LE(34);
  const numChannels = buffer.readUInt16LE(22);

  // データチャンクを探す
  let dataOffset = 12;
  while (dataOffset < buffer.length - 8) {
    const chunkId = buffer.toString("ascii", dataOffset, dataOffset + 4);
    const chunkSize = buffer.readUInt32LE(dataOffset + 4);

    if (chunkId === "data") {
      const bytesPerSample = (bitsPerSample / 8) * numChannels;
      const numSamples = chunkSize / bytesPerSample;
      return numSamples / sampleRate;
    }

    dataOffset += 8 + chunkSize;
  }

  // フォールバック: ファイルサイズから推測
  const dataSize = buffer.length - 44;
  const bytesPerSecond = sampleRate * (bitsPerSample / 8) * numChannels;
  return dataSize / bytesPerSecond;
}

/**
 * VOICEVOX APIで音声を生成
 */
async function generateVoice(
  text: string,
  speakerId: number,
  outputPath: string,
  config: ReturnType<typeof loadConfig>
): Promise<number> {
  const endpoint = getVoicevoxEndpoint();

  // 1. Audio Query を取得
  const queryUrl = `${endpoint}/audio_query?text=${encodeURIComponent(text)}&speaker=${speakerId}`;
  const queryRes = await fetch(queryUrl, { method: "POST" });

  if (!queryRes.ok) {
    throw new Error(`Audio Query failed: ${queryRes.status} ${queryRes.statusText}`);
  }

  const query = await queryRes.json();

  // 音声パラメータを適用
  const defaults = config.voicevox.defaults;
  query.speedScale = defaults.speedScale;
  query.pitchScale = defaults.pitchScale;
  query.intonationScale = defaults.intonationScale;
  query.volumeScale = defaults.volumeScale;

  // 2. 音声合成
  const synthesisUrl = `${endpoint}/synthesis?speaker=${speakerId}`;
  const synthesisRes = await fetch(synthesisUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(query),
  });

  if (!synthesisRes.ok) {
    throw new Error(`Synthesis failed: ${synthesisRes.status} ${synthesisRes.statusText}`);
  }

  const wavBuffer = await synthesisRes.arrayBuffer();
  fs.writeFileSync(outputPath, Buffer.from(wavBuffer));

  // 3. 再生時間を計算（フレーム数）
  const durationSec = getWavDuration(outputPath);
  const fps = config.video.fps;
  const durationInFrames = Math.ceil(durationSec * fps) + 5; // +5 frame buffer

  return durationInFrames;
}

/**
 * script.ts を更新
 */
function updateScriptFile(scriptData: ScriptData): void {
  const output = `// 自動生成ファイル - 手動編集しないでください
// Generated by scripts/parse-markdown.ts
// Updated by scripts/generate-voices.ts

import type { ScriptData } from "../types.js";

export const scriptData: ScriptData = ${JSON.stringify(scriptData, null, 2)};
`;

  fs.writeFileSync(SCRIPT_PATH, output, "utf-8");
}

/**
 * メイン処理
 */
async function main() {
  console.log("VOICEVOX 音声生成を開始します...");

  const config = loadConfig();

  // script.ts を動的にインポート
  const scriptModule = await import("../src/data/script.js");
  const scriptData: ScriptData = { ...scriptModule.scriptData };

  // 出力ディレクトリを作成
  if (!fs.existsSync(VOICES_DIR)) {
    fs.mkdirSync(VOICES_DIR, { recursive: true });
  }

  // VOICEVOX 接続確認
  const voicevoxEndpoint = getVoicevoxEndpoint();
  try {
    const res = await fetch(`${voicevoxEndpoint}/version`);
    if (!res.ok) throw new Error("Connection failed");
    const version = await res.text();
    console.log(`  VOICEVOX Engine: ${version}`);
  } catch (error) {
    console.error(`Error: VOICEVOX に接続できません (${voicevoxEndpoint})`);
    console.error("  VOICEVOX を起動してから再実行してください");
    process.exit(1);
  }

  const durations: DurationsJson = {};
  let totalFrames = 0;

  // 各セグメントの音声を生成
  for (const segment of scriptData.segments) {
    const charConfig = getCharacterConfig(segment.character);
    const speakerId = charConfig?.voiceId ?? 3;

    const outputPath = path.join(VOICES_DIR, path.basename(segment.voiceFile));

    console.log(`  [${segment.id}] ${segment.character}: ${segment.voiceText.slice(0, 30)}...`);

    try {
      const durationInFrames = await generateVoice(
        segment.voiceText,
        speakerId,
        outputPath,
        config
      );

      segment.durationInFrames = durationInFrames;

      const durationSec = getWavDuration(outputPath);
      durations[path.basename(segment.voiceFile)] = {
        durationSec,
        durationInFrames,
      };

      totalFrames += durationInFrames + segment.pauseAfter;

      console.log(`       → ${durationSec.toFixed(2)}秒 (${durationInFrames} frames)`);
    } catch (error) {
      console.error(`  Error: セグメント ${segment.id} の生成に失敗しました`);
      console.error(`         ${error}`);
    }
  }

  // totalDurationInFrames を更新
  scriptData.totalDurationInFrames = totalFrames;

  // durations.json を出力
  fs.writeFileSync(DURATIONS_PATH, JSON.stringify(durations, null, 2), "utf-8");
  console.log(`  → ${DURATIONS_PATH} に出力しました`);

  // script.ts を更新
  updateScriptFile(scriptData);
  console.log(`  → ${SCRIPT_PATH} を更新しました`);

  console.log(`\n音声生成完了: ${scriptData.segments.length} セグメント`);
  console.log(`合計時間: ${(totalFrames / config.video.fps).toFixed(2)}秒 (${totalFrames} frames)`);
}

main().catch(console.error);
